FROM nginx

RUN echo "deb http://ftp.debian.org/debian stretch-backports main" >> /etc/apt/sources.list

RUN apt update && \
    apt-get install -y ruby python-certbot-nginx -t stretch-backports

COPY ./scripts/ /scripts
RUN chmod +x /scripts/*.sh

# Copy configuration files
RUN rm -f /etc/nginx/conf.d/*

COPY ./installer/confs/nginx /etc/nginx

# used for webroot authentication 
RUN mkdir -p /data

CMD ["/bin/bash", "/scripts/get_certificate.sh"]