FROM nginx

RUN apt update && \
    apt install -y ruby python python-dev libffi6 libffi-dev libssl-dev curl build-essential && \
    curl -L 'https://bootstrap.pypa.io/get-pip.py' | python && \
    pip install -U cffi certbot certbot-nginx && \
    apt remove --purge -y python-dev build-essential libffi-dev libssl-dev curl && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


COPY ./scripts/ /scripts
RUN chmod +x /scripts/*.sh

# Copy configuration files
RUN rm -f /etc/nginx/conf.d/*

COPY ./installer/confs/nginx /etc/nginx

CMD ["/bin/bash", "/scripts/get_certificate.sh"]